apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: openvax/neoantigen-vaccine-pipeline:0.6.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-ec", "sleep 1000"]

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-1
  labels:
    app: busybox1
spec:
  containers:
    - name: busybox1
      image: hremon331046/neoantigen-vaccine-pipeline:d0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-ec", "sleep 1000"]