apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  labels:
    app: busybox1
spec:
  containers:
    - name: busybox1
      image: docker.io/hremon331046/neoantigen-vaccine-pipeline:d0.4.2-mhc2-test-v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-ec", "sleep 10000"]