apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: "default-provisioner"
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - "c6i.8xlarge"
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        - arm64
  limits:
    resources:
      cpu: "64"
      memory: "200Gi"
  provider:
    instanceProfile: "eks-08c30e12-4d82-65a1-5f68-6a78c27d2ee3"
    subnetSelector:
      aws-ids: "subnet-088f4af5f33751b4c"
    securityGroupSelector:
      kubernetes.io/cluster/breakbio-cluster: "owned"
      Name: "eks-cluster-sg-breakbio-cluster-47860694"
      aws:eks:cluster-name: "breakbio-cluster"
  ttlSecondsAfterEmpty: 60